### ISSUE TITLE
Ensure gem with require doesn't actually require the gem

### ISSUE THREAD

**Issue by agrare** [ManageIQ/bundler-inject#10]
With byebug in the main Gemfile of an application with `require => false`, and `ensure_gem "byebug", :require => "byebug"` the gem isn't actually getting required.

**Comment by Fryguy** [comment]
Weird, this actually works for me.

**Comment by agrare** [comment]
Hm it works for me too, if I can find a repro scenario I'l re-open this

**Comment by Fryguy** [comment]
I just hit this locally...will try to isolate.

**Comment by Fryguy** [comment]
Never got another repro scenario, so I'm going to close this.
