### ISSUE TITLE
Use `Bundler::Settings` for `warn_override_gem`

### ISSUE THREAD

**Issue by NickLaMuro** [ManageIQ/bundler-inject#5]
Using `ENV["RAILS_ENVIRONMENT"] == "production"` is too Rails™ specific for this project, and kind of a hidden feature.

https://github.com/ManageIQ/bundler-inject/blob/feb5e6992387970ea0d7c17797ac267386850d25/lib/bundler/inject/dsl_patch.rb#L66

It would be much better to hook into the `Bundler::Settings`, which is already something available and should be generic enough to work with our plugin:

```ruby
return if Bundler.settings["bundler-inject.disable_warn_override_gem_output"]
```

Then you can run:

```console
$ bundle config bundler-inject.disable_warn_override_gem_output true
$ irb
irb(main):001:0> require 'bundler/setup'
=> true
irb(main):002:0> Bundler.settings["bundler-inject.disable_warn_override_gem_output"]
=> "true"
irb(main):003:0>
```

And make use of the disabling setting that way.  Can be an environment variable as well (though, we might want to consider it without the `-` since that isn't a valid ENV var variable in most shells...): 

```console
$ bundle config --delete bundler-inject.disable_warn_override_gem_output
$ irb
irb(main):001:0> require 'bundler/setup'
=> true
irb(main):002:0> Bundler.settings["bundler-inject.disable_warn_override_gem_output"]
=> nil
irb(main):003:0> exit
$ env "BUNDLE_BUNDLER-INJECT__DISABLE_WARN_OVERRIDE_GEM_OUTPUT=true" irb
irb(main):001:0> require 'bundler/setup'
=> true
irb(main):002:0> Bundler.settings["bundler-inject.disable_warn_override_gem_output"]
=> "true"
irb(main):003:0>
```

**Comment by Fryguy** [comment]
That's quite the env var name 😆  `BUNDLE_BUNDLER-INJECT__DISABLE_WARN_OVERRIDE_GEM_OUTPUT`

**Comment by NickLaMuro** [comment]
> That's quite the env var name...

Yeah, but it was a shared config, so I didn't want it to be something that was overwritten.

Also it's a "Working Title™".  "PR's welcome"
